spring:
  datasource:
    url: jdbc:mysql://10.12.70.25:3306/dicmp_test
    username: root
    password: 1mqay3zXSW!
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 50
      max-idle: 50
      # max-active: 250
      min-idle: 5
      max-wait-millis: 10000
      validation-query: select 1
      # connection-properties: characterEncoding=utf8
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    serialization:
      indent-output: true
  cache:
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterAccess=5s,expireAfterWrite=10s,refreshAfterWrite=5s
  profiles:
   active: dev1
logging:
  level:
    root: info
  file: ./spring-boot-caffeine.log
server:
  port: 8090



